# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Install dependencies if any; skip if not needed
# COPY package*.json ./
# RUN npm install --ignore-scripts

# Copy source code if necessary (not needed as we rely on npx)
# COPY . .

# Expose any port if required (not specified in README)

# Start the Brave Search MCP server using npx
CMD ["npx", "-y", "@modelcontextprotocol/server-brave-search"]
